show_downloads: true

name: Programmation Avancée 

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: ISSAE Architect theme

description: ISSAE Architect is a theme for Cnam Liban GitHub Pages

google_analytics: UA-29708002-2

plugins:
  - jekyll-seo-tag

remote_theme: ISSAE/architect
